services:
  chatbot:
    build: .
    container_name: chatbot
    env_file:
      - .env
    stdin_open: true
    tty: true
    ports:
      - "8501:8501"
    volumes:
      - ./chroma_chat_memory:/app/chroma_chat_memory
